//@version=6
strategy("Pivot Vwap confluence entry system", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)
pivot = request.security(syminfo.tickerid, "D", (high + low + close) / 3.0)
vwapValue = ta.vwap(hlc3)
longSignal = ta.crossover(close, pivot) and close > vwapValue
shortSignal = ta.crossunder(close, pivot) and close < vwapValue
if longSignal
    strategy.entry("Long", strategy.long)
if shortSignal
    strategy.entry("Short", strategy.short)
if ta.crossunder(close, vwapValue)
    strategy.close("Long")
if ta.crossover(close, vwapValue)
    strategy.close("Short")
plot(pivot, "Daily Pivot", color=color.orange)
plot(vwapValue, "VWAP", color=color.blue)
