//@version=6
strategy("Gold HFT - Hybrid MT5 Final", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)
bbBasis = ta.sma(close, 20)
bbDev = ta.stdev(close, 20) * 2.0
upper = bbBasis + bbDev
lower = bbBasis - bbDev
rsiValue = ta.rsi(close, 7)
if ta.crossover(close, lower) and rsiValue < 35
    strategy.entry("Long", strategy.long)
if ta.crossunder(close, upper) and rsiValue > 65
    strategy.entry("Short", strategy.short)
if ta.cross(close, bbBasis)
    strategy.close_all()
plot(upper, "Upper", color=color.red)
plot(lower, "Lower", color=color.green)
plot(bbBasis, "Basis", color=color.blue)
